# pyproject.toml
[tool.pytest]
pythonpath = ["src"]
minversion = "9.0"
addopts = [
    "-ra",
    "-q",
    "--cov=src",
    "--cov-report=term-missing",
    "--cov-report=html:htmlcov",
    "-vv",
]
testpaths = ["tests"]
timeout = 30

[project.optional-dependencies]
test = [
    "pytest",
    "pytest-cov",
]